env: "CouchmovingTrajectory-v0"
device: "cuda"
env_cfg:
  early_success: False
  task_agnostic: False
  reward_type: "trajectory"
  trajectories: "datasets/couchmoving/couch_4_corridorrange_12_20/dataset_train_ids_2400.npy"
  trajectories_dataset: "datasets/couchmoving/couch_4_corridorrange_12_20/dataset_teacher.pkl"
  max_trajectory_skip_steps: 15
  offscreen_only: True
  env_rew_weight: 0.5
  exclude_target_state: True
  fixed_max_ep_len: 150
  target_next_chamber: True
  sub_goals: False

exp_cfg:
  algo: ppo
  seed: 0
  n_envs: 20


  gae_lambda: 0.97
  target_kl: 0.15
  log_std_scale: -0.5
  pi_lr: 3e-4
  vf_lr: 3e-4

  accumulate_grads: False
  #ppo configs
  epochs: 50000
  critic_warmup_epochs: 0
  update_iters: 3
  steps_per_epoch: 20000
  batch_size: 1024
  eval_freq: 50
  eval_save_video: True
  max_ep_len: 150

  dapg: False

logging_cfg:
  exp_name: transformer_scratch
  wandb: False
  tensorboard: True
  log_freq: 1

model_cfg:
  type: "TranslationTransformer"
  pretrained_actor_weights: None
  pretrained_critic_weights: None

  state_dims: 18 # merges past action into stacked frame instead of encoding actions separately
  act_dims: 3
  teacher_dims: 2

  max_time_steps: 1024
  # below should also be merged into dataset_cfgs
  max_student_length: 300
  max_teacher_length: 50
  trajectory_sample_skip_steps: 3
  # equivalent to positional embeddings
  timestep_embeddings: False
  teacher_timestep_embeddings: False
  
  # whether to include past student actions into the student stack frames fed into transformer
  use_past_actions: False
  # whether to use layer normalization after the initial embedding layers of student/teacher states and student actions
  embed_layer_norm: True

  # translation model specific configs
  stack_size: 5
  state_embedding_hidden_sizes: (64,)
  state_embedding_activation: 'relu'
  final_mlp_hidden_sizes: (128, 128)
  final_mlp_activation: 'relu'
  
  final_mlp_action_pred_activation: 'tanh'
  final_mlp_state_pred_activation: 'tanh'
  encoder_config:
    type: "state"
  # gpt2 specific https://huggingface.co/docs/transformers/model_doc/gpt2#transformers.GPT2Config
  transformer_config:
    n_head: 2
    n_layer: 4
    activation_function: 'gelu_new'
    resid_pdrop: 0.1 
    embd_pdrop: 0.1
    attn_pdrop: 0.1